/**
 * PROJECTS
 * @type {string}
 */
export const PROJECTS_REQUEST = "PROJECTS_REQUEST";
export const PROJECTS_SUCCESS = "PROJECTS_SUCCESS";
export const PROJECTS_GET_SINGLE = "PROJECTS_GET_SINGLE";
export const PROJECT_DELETE_REQUEST = "PROJECT_DELETE_REQUEST";
export const PROJECT_DELETE_SUCCESS = "PROJECT_DELETE_SUCCESS";
export const PROJECT_DELETE_FAILURE = "PROJECT_DELETE_FAILURE";
export const PROJECT_ADD_REQUEST = "PROJECT_ADD_REQUEST";
export const PROJECT_ADD_SUCCESS = "PROJECT_ADD_SUCCESS";
export const PROJECT_ADD_FAILURE = "PROJECT_ADD_FAILURE";
export const PROJECT_GET_SINGLE = "PROJECT_GET_SINGLE";

/**
 * TERMINALS
 */

export const TERMINALS_FETCH_REQUEST = "TERMINALS_FETCH_REQUEST";
export const TERMINALS_FETCH_SUCCESS = "TERMINALS_FETCH_SUCCESS";
export const TERMINALS_FETCH_FAILURE = "TERMINALS_FETCH_FAILURE";

export const TERMINAL_REMOVE_REQUEST = "TERMINAL_REMOVE_REQUEST";
export const TERMINAL_REMOVE_SUCCESS = "TERMINAL_DELETE_SUCCESS";
export const TERMINAL_REMOVE_FAILURE = "TERMINAL_DELETE_FAILURE";

export const TERMINAL_ADD_REQUEST = "TERMINAL_ADD_REQUEST";
export const TERMINAL_ADD_SUCCESS = "TERMINAL_ADD_SUCCESS";
export const TERMINAL_ADD_FAILURE = "TERMINAL_ADD_FAILURE";



/**
 * Auth
 * @type {string}
 */

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGOUT = "LOGOUT";
