/**
 * PROJECTS
 * @type {string}
 */
export const PROJECTS_GET_ALL = 'PROJECTS_GET_ALL';
export const PROJECTS_GET_SINGLE = 'PROJECTS_GET_SINGLE';
export const PROJECT_DELETE = 'PROJECT_DELETE';
export const PROJECT_ADD_REQUEST = 'PROJECT_ADD_REQUEST';
export const PROJECT_ADD_SUCCESS = 'PROJECT_ADD_SUCCESS';
export const PROJECT_ADD_FAILURE = 'PROJECT_ADD_FAILURE';